-- Continental Intelligence Platform — Supabase schema
-- Mirrors the pattern used in jmk-tender-monitor-ai: one raw ingestion table
-- per source, plus a normalized view the API/dashboard reads from.

create table if not exists countries (
  iso3 text primary key,
  name text not null,
  region text not null,
  continent text not null
);

create table if not exists indicators (
  id text primary key,           -- e.g. 'gdpPerCapita'
  source text not null check (source in ('worldbank','who')),
  source_code text not null,     -- e.g. 'NY.GDP.PCAP.CD' or 'WHOSIS_000001'
  label text not null,
  unit text,
  module text not null           -- 'economic' | 'human' | 'health' | 'environment' | 'governance'
);

create table if not exists indicator_values (
  id bigserial primary key,
  iso3 text not null references countries(iso3),
  indicator_id text not null references indicators(id),
  year int not null,
  value numeric,
  fetched_at timestamptz not null default now(),
  unique (iso3, indicator_id, year)
);

create index if not exists idx_indicator_values_lookup
  on indicator_values (indicator_id, iso3, year desc);

-- Cached AI-generated executive briefings, so /briefing doesn't call the
-- model on every request — regenerated by the scheduled ingestion job.
create table if not exists briefings (
  id bigserial primary key,
  iso3 text not null references countries(iso3),
  generated_at timestamptz not null default now(),
  summary text not null,
  risk_flags jsonb,
  model text not null
);

create index if not exists idx_briefings_latest
  on briefings (iso3, generated_at desc);

-- Convenience view: latest value per country/indicator, used by the
-- dashboard's /indicators/{iso3} endpoint.
create or replace view latest_indicator_values as
select distinct on (iso3, indicator_id)
  iso3, indicator_id, year, value, fetched_at
from indicator_values
order by iso3, indicator_id, year desc;
